### ISSUE TITLE
Cannot use with macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by yangmillstheory** [kimar/DeveloperExcuses#11]
![image](https://user-images.githubusercontent.com/2729079/32209521-d385cb28-bdc5-11e7-834b-b2ffe882c500.png)

After downloading and opening the `.saver` file, the preview in System Preferences says I can't use it with this version of the OS. I wish I had taken a screenshot previously; now I can't even see preview the screen saver.

**Comment by kimar** [comment]
This is weird as the deployment target is set to `10.9`, would you mind trying it with this release? https://github.com/kimar/DeveloperExcuses/releases/tag/2.1.1

**Comment by clayreimann** [comment]
Just saw this with release `2.1.1` running on `10.13.2 (17C88)`. I'll try compiling it locally and seeing if that clears up the issue…

**Comment by yangmillstheory** [comment]
@kimar , the screen saver works, but the bug is that the following leads one to think it won't work:

![image](https://user-images.githubusercontent.com/2729079/34084145-981a1f9a-e330-11e7-891d-d7a827e342e5.png)

This is macOS 10.13.1., with release 2.1.1.

**Comment by clayreimann** [comment]
That’s what I see, and it doesn’t work either

Thanks,
Clay

**Comment by pschneider** [comment]
I see this preview too, but activating the screen saver (via Hot Corner) works as expected. Only the preview button does not work.

**Comment by kimar** [comment]
Might be related to this rdar -> http://www.openradar.me/25569037

**Comment by kimar** [comment]
I'm going to close this issue as it seems to be related to rdar://25569037 .
