### ISSUE TITLE
Not supported on Mac High Sierra

### ISSUE THREAD

**Issue by abhayjatindoshi** [kimar/DeveloperExcuses#12]

**Comment by kimar** [comment]
Please check if it‘s related to this issue, which is a bug on the OS side rather than in the Screensaver: https://github.com/kimar/DeveloperExcuses/issues/11

**Comment by abhayjatindoshi** [comment]
Yes. It is sorry for the trouble.

**Comment by kimar** [comment]
No worries at all :-)
