### ISSUE TITLE
Add option for font size

### ISSUE THREAD

**Issue by BennX** [kimar/DeveloperExcuses#13]
I'd love to see an option to change the font size.

**Comment by kimar** [comment]
This is currently defined in the OnelinerKit Framework (https://github.com/kimar/OnelinerKit), but I'd love to have this customizable and exposed as an option in the ScreenSaver as well.

**Comment by kimar** [comment]
I'm going to close this issue and shut down issues for this project now.

As this is only a side-project of mine I might or might not fix it at some point in time, however every developer is more than welcome to contribute to this repository by raising a PR.
