### ISSUE TITLE
Not supported on High Sierra

### ISSUE THREAD

**Issue by freitasskeeled** [kimar/DeveloperExcuses#14]
Hi there,

 I'm using MacOS High Sierra and after the install I get the following message: "Cannot use with this version".

Do you have a schedule updated release planned?

Thanks

**Comment by mwtsn** [comment]
I second this, I'd love this as my screensaver :)

**Comment by kimar** [comment]
Hi, this is not an issue with the screensaver and, apart from the misleading error message, it’s working fine on High Sierrs, please see #11.
