### ISSUE TITLE
not working with mac os mojave

### ISSUE THREAD

**Issue by mhauens** [kimar/DeveloperExcuses#16]

**Comment by bhean** [comment]
I was going to put the same issue right now... :+1:

**Comment by kimar** [comment]
Hi, could you please elaborate on the issue? Is this likely this issue that's coming up with every new macOS version (which is related to Swift)? https://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by kimar** [comment]
Please let me know if you're using the precompile binary (likely to fail due to different Swift runtime) or building the screensaver yourself.

**Comment by mhauens** [comment]
I used the .saver file

**Comment by Luzifer** [comment]
I've tried finding any log output relating to this: Nothing… The name of the screensaver is mentioned once in the machine logs, other logs doesn't look suspicious… Maybe you got more luck and a helpful log output on your machine…

**Comment by Luzifer** [comment]
Sadly the solution from that thread does not work for us:

> And then, all of a sudden, it works...

Tried that… 😂

**Comment by kimar** [comment]
Looks like the issue is linked to how OnelinerKit is dependent on (using Carthage). I've added onelinerkit directly and fixed the issue. 
In the small preview it still doesn't show up correctly (seems to be cached by macOS) but when running the screensaver it works fine again. I've attached a new zip with the `.saver` binary, can anyone confirm please?

**Comment by reden87** [comment]
thanks @kimar for the fix! you're awesome 👍

**Comment by kimar** [comment]
@reden87 thanks@ You're welcome :-) Glad you like the screensaver.

**Comment by simplenotezy** [comment]
Is this considered an excuse? 😀 
![image](https://user-images.githubusercontent.com/3786627/47670029-878fb480-dbac-11e8-9c68-f87c6c3dc6d1.png)

**Comment by kimar** [comment]
@simplenotezy 

Haha, no not really.

Are you using Mojave? Did you try this release?
https://github.com/kimar/DeveloperExcuses/releases/tag/2.1.2

I confirmed it's working on Mojave on at least two different machines.

**Comment by bhean** [comment]
The latest version is working fine in my Mojave, thank you! :+1:

**Comment by DanielHilton** [comment]
I've updated to latest and this is still showing the 'You cannot use the..." message when i run the screensaver

**Comment by kimar** [comment]
@DanielHilton did you try deleting the old one, then installing the new one? It's a slightly opaque thing but it's supposed to work. Also are you using Mojave?

**Comment by DanielHilton** [comment]
@kimar thanks that did the trick 😃

**Comment by kimar** [comment]
Great!
