### ISSUE TITLE
Unindentified developer

### ISSUE THREAD

**Issue by simplenotezy** [kimar/DeveloperExcuses#17]
I need to run the saver as administrator.

![image](https://user-images.githubusercontent.com/3786627/46338423-70eb5180-c630-11e8-99b9-2bbe06d5f24c.png)

It would be nice if I didn't need to.

**Comment by kimar** [comment]
I'll be able to release a properly signed version. Thanks!

**Comment by JimmyMultani** [comment]
I'm still getting this issue on Catalina.

**Comment by kimar** [comment]
@JimmyMultani unfortunately it's not feasible to just sign a `.saver` file but I'd need to wrap it inside an installer package. As I don't know when I'll find some time to do so, please for now use the "Option+Click" workaround, e.g. use the Right-Click Context Menu and Click "Open" this time you should be able to Open the Screensaver.

**Comment by JimmyMultani** [comment]
Did not know about that. I'll give it a try, thank you!

**Comment by JimmyMultani** [comment]
Unfortunately, the method you mentioned still does not work. :(
