### ISSUE TITLE
Bigger font

### ISSUE THREAD

**Issue by simplenotezy** [kimar/DeveloperExcuses#18]
Would be super awesome if the text filled the whole screen. This screenshot is from UltraFine 5K screen.

<img width="2560" alt="screen shot 2018-10-02 at 10 48 06" src="https://user-images.githubusercontent.com/3786627/46338558-c3c50900-c630-11e8-8100-d68c3b35bc03.png">

**Comment by gergo-aym** [comment]
This issue is duplication of #13

**Comment by kimar** [comment]
As @gergo-aym said. LEt's tackle this together with #13.
