### ISSUE TITLE
Not compatible with Mojave

### ISSUE THREAD

**Issue by simplenotezy** [kimar/DeveloperExcuses#19]

**Comment by bhean** [comment]
This issue is duplicated: https://github.com/kimar/DeveloperExcuses/issues/16

**Comment by kimar** [comment]
Haha, no not really.

Are you using Mojave? Did you try this release? 
https://github.com/kimar/DeveloperExcuses/releases/tag/2.1.2

I confirmed it's working on Mojave on at least two different machines.
