### ISSUE TITLE
No output when building

### ISSUE THREAD

**Issue by andersfischernielsen** [kimar/DeveloperExcuses#2]
Maybe I'm just stupid, but I simply can't get the `.xcodeproj` to build into a `.saver`. 

I've converted to project to ARC, made some changes (which build sucessfully), but when I build (`cmd+B`) I don't get any `.saver` output file. 

Could you give me some directions on how to build the project?

**Comment by kimar** [comment]
Hm, weird, just tried it out again. Check out, build and I can find the `.saver` in the products section:

![screen shot 2016-03-23 at 3 27 40 pm](https://cloud.githubusercontent.com/assets/126418/13975675/ff26902e-f10b-11e5-8e60-53f461c4abf4.png)

(Btw I've just pushed changes with ARC enabled, didn't see much light in the past years, could also need some refactoring)
