### ISSUE TITLE
Text displayed really small

### ISSUE THREAD

**Issue by hanspeteroliver** [kimar/DeveloperExcuses#20]
With the latest release, on Mojave 10.15.2 the screensaver is way too small for the screen. This happens on my Mac's screen as well as on external screens. See attached screenshots 
<img width="1680" alt="mac_display_retina copy" src="https://user-images.githubusercontent.com/30975982/73258583-4da1c980-41c6-11ea-9c5a-55ac2ee96f70.png">
<img width="2560" alt="external_display_uhd copy" src="https://user-images.githubusercontent.com/30975982/73258625-67431100-41c6-11ea-9c20-8f8b19657b30.png">

Also, I don't think #18 should have been marked as a duplicate with issue #13 since the font used to be normal-sized in previous versions, while #13 is more like an optional feature to fit everyone's preference. But I really can't imagine the font is supposed to be that small, is it? Like this is a deal-breaker for me and many colleagues :/

**Comment by hanspeteroliver** [comment]
Any fixed version or something out there?

**Comment by kimar** [comment]
Hi, there has certainly been a change ein behaviour of fonts in the macOS `ScreenSaverView` beginning with Catalina. 

I'm going to close this issue and shut down issues for this project now.

As this is only a side-project of mine I might or might not fix it at some point in time, however every developer is more than welcome to contribute to this repository by raising a PR.
