### ISSUE TITLE
Any tips for how to rewire this to work with different text?

### ISSUE THREAD

**Issue by ameliariely** [kimar/DeveloperExcuses#5]
Looking to create a version with my own input.

**Comment by clayreimann** [comment]
You'd want to look at the [fetchNext](https://github.com/kimar/DeveloperExcuses/blob/master/DeveloperExcuses/DeveloperExcusesView.swift#L120-L145) function.

**Comment by kimar** [comment]
@ameliariely I've refactored most of the UI and fetching logic into a separate framework that can be used to create simple, text based, screensavers in no time. You can find it here: https://github.com/kimar/OnelinerKit

Also I'm now using this in DeveloperExcuses, just head over to https://github.com/kimar/DeveloperExcuses/blob/master/DeveloperExcuses/DeveloperExcusesView.swift to see how it's implemented.
