### ISSUE TITLE
Multiple refresh when plugged in an external monitor 

### ISSUE THREAD

**Issue by henryzx** [kimar/DeveloperExcuses#9]
quotes refreshes 2 times. like this:
`q1 ->(only shows for 1/2 sec) -> q2 ---->(few normal secs delay) ----> q3 ->(1/2 sec again) q4`

very annoying.

btw, two monitors shows different quotes. It's not very user friendly. please refer to apple's stock 'word of the day' screensaver.

**Comment by kimar** [comment]
Hi, would you mind trying it out with v2.1.1 again? https://github.com/kimar/DeveloperExcuses/releases/tag/2.1.1

**Comment by kimar** [comment]
Fixed in https://github.com/kimar/DeveloperExcuses/commit/429f79b38f6c591f68d98953df5eaeefe6a46cdb
